# Generated by Django 3.1 on 2020-08-26 01:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Invalid category name'), django.core.validators.MaxLengthValidator(55, 'Invalid category name')])),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, 'Invalid category name'), django.core.validators.MaxLengthValidator(55, 'Invalid category name')])),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.categoria')),
            ],
        ),
    ]
