# Generated by Django 3.1 on 2020-08-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curso',
            old_name='id_categoria',
            new_name='categoria',
        ),
    ]
