# Generated by Django 3.1 on 2020-08-26 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='progresovideo',
            name='dia',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
