# Generated by Django 3.1 on 2020-08-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_auto_20200826_0226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='progresovideo',
            old_name='id_categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='progresovideo',
            old_name='id_curso',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='progresovideo',
            old_name='id_inscripcion',
            new_name='inscripcion',
        ),
        migrations.RenameField(
            model_name='progresovideo',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
